# Generated by Django 3.2.7 on 2021-09-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Heartdisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('sex', models.IntegerField(default=0)),
                ('cp', models.IntegerField(default=0)),
                ('trestbps', models.IntegerField(default=0)),
                ('chol', models.IntegerField(default=0)),
                ('fbs', models.IntegerField(default=0)),
                ('restecg', models.IntegerField(default=1)),
                ('thalach', models.IntegerField(default=0)),
                ('exang', models.IntegerField(default=0)),
                ('oldpeak', models.IntegerField(default=0)),
                ('slope', models.IntegerField(default=0)),
                ('ca', models.IntegerField(default=0)),
                ('thal', models.IntegerField(default=0)),
            ],
        ),
    ]
